### PR TITLE
A New Chart Using Hooks

### PR DESCRIPTION
**Pull request by sudermanjr**
* Re-wrote the chart to use post-install/post-upgrade hook to install the custom resource.   Huge thanks to @ejether for writing the actual hook that I blatantly stole from his branch.  
* Renamed some variables to match helm best practices.
* Removed the need for running the chart twice, and removed that node from the readme
* Removed the sub-charts as they were totally unnecessary.
* Tested on initial install and on subsequent upgrades
* Tested with autohelm
* TODO: Test on existing install to make sure it doesn't break them (it should)

### CODE REVIEW

**Comment by sudermanjr** [comment]
I installed using the current master chart, created an rbacdefinition manually, then  installed the new chart with an identical user in the chart config.  Both kubeconfigs generated were identical.  This means that we _should_ be safe to merge this without breaking existing implementations.

**Comment by sudermanjr** [comment]
TODO: 
Move post-install hook to use separate service account.

**Comment by ejether** [comment]
I like the idea, but don't consider it a blocker.

**Comment by sudermanjr** [comment]
@robscott Per your concerns I moved the post-hook job to run using it's own service account that only has access to rbacdefinitions.  Tested and working.

**Pull request merged**
